"""Sphinx build for the lib_loans reference corpus.

A live demonstration of what disco-agent renders from a ``discovery/`` tree.
``confdir`` is ``tests/golden/docs``, so ``disco_agent.app.sphinx`` resolves
the project from ``confdir.parent`` (= ``tests/golden``, which carries the
``[tool.disco]`` table). The per-source and per-referent pages under
``_evidence/`` are generated by ``make docs-corpus`` before the build and are
gitignored; the hand-written index pages here wire them into navigation.
"""

from __future__ import annotations

import os
import sys

# lib_loans is a fixture package (tests/golden/src/lib_loans), not installed.
# Put it on the path so the domain-glossary directive can import it to read
# the class/module docstrings that are the domain canonical summaries.
sys.path.insert(0, os.path.abspath("../src"))

project = "lib_loans — rendered discovery corpus"
author = "GoSource"
copyright = "GoSource"  # noqa: A001

extensions = ["disco_agent.app.sphinx"]

html_theme = "alabaster"
html_title = "lib_loans corpus"

# _canonical / _glossary_terms / _personas fragments (if generated) are
# spliced into hand-authored pages elsewhere; this demonstrator doesn't author
# those, so keep any stray generated fragments out of the standalone build.
exclude_patterns = [
    "_build",
    "_canonical",
    "_glossary_terms",
    "_personas",
    "Thumbs.db",
    ".DS_Store",
]
